// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyNHD1-a80uZ22hGUt5xRA0CKF6hqYGp8',
    appId: '1:423866413064:web:6903e00fa1be5e66d5a1bd',
    messagingSenderId: '423866413064',
    projectId: 'localtrade-568cd',
    authDomain: 'localtrade-568cd.firebaseapp.com',
    storageBucket: 'localtrade-568cd.firebasestorage.app',
    measurementId: 'G-KK7T8HQ1JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYy6SsLE6C-DOrOdlSPpFmLtTpxbwCQwg',
    appId: '1:423866413064:android:436bbdb8a15d637bd5a1bd',
    messagingSenderId: '423866413064',
    projectId: 'localtrade-568cd',
    storageBucket: 'localtrade-568cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnM3QylY-cbZDjCWqXQ0yF2jJsJTTAzFM',
    appId: '1:423866413064:ios:bf6e37e86319effdd5a1bd',
    messagingSenderId: '423866413064',
    projectId: 'localtrade-568cd',
    storageBucket: 'localtrade-568cd.firebasestorage.app',
    iosBundleId: 'com.example.localtradeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnM3QylY-cbZDjCWqXQ0yF2jJsJTTAzFM',
    appId: '1:423866413064:ios:bf6e37e86319effdd5a1bd',
    messagingSenderId: '423866413064',
    projectId: 'localtrade-568cd',
    storageBucket: 'localtrade-568cd.firebasestorage.app',
    iosBundleId: 'com.example.localtradeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyNHD1-a80uZ22hGUt5xRA0CKF6hqYGp8',
    appId: '1:423866413064:web:c8400bfe37a0cadfd5a1bd',
    messagingSenderId: '423866413064',
    projectId: 'localtrade-568cd',
    authDomain: 'localtrade-568cd.firebaseapp.com',
    storageBucket: 'localtrade-568cd.firebasestorage.app',
    measurementId: 'G-TE14RFE3MQ',
  );
}
